### ISSUE TITLE
Private github atom feed token leaked in repo

### ISSUE THREAD

**Issue by mcpherrinm** [piratas/wiki-piratas#1]
I did a github search for Github's private.atom and found what seems to be a valid token in a repository. This may leak information about private repositories you follow at least.

https://github.com/piratas/wiki-piratas/blob/274bac1e5fa452cb400bf22d2ef8c351ffeb7c1f/wiki/gti/not%C3%ADcias/index.mdwn?plain=1#L33

The only way to change it is to reset your password, as far as I know.

**Comment by iuriguilherme** [comment]
It is. The website is no longer online but the key was valid all those years. Good job and thank you.
